### ISSUE TITLE
ModuleNotFoundError: No module named 'termios'

### ISSUE THREAD

**Issue by conradstorz** [nschloe/tiptop#33]
$ tiptop
Traceback (most recent call last):
  File "C:\Users\Conrad\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Conrad\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Conrad\AppData\Local\Programs\Python\Python38-32\Scripts\tiptop.exe\__main__.py", line 4, in <module>       
  File "C:\Users\Conrad\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tiptop\__init__.py", line 1, in <module> 
    from ._app import run
  File "C:\Users\Conrad\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tiptop\_app.py", line 1, in <module>     
    from textual.app import App
  File "C:\Users\Conrad\AppData\Local\Programs\Python\Python38-32\lib\site-packages\textual\app.py", line 27, in <module>    
    from ._linux_driver import LinuxDriver
  File "C:\Users\Conrad\AppData\Local\Programs\Python\Python38-32\lib\site-packages\textual\_linux_driver.py", line 9, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'

**Comment by conradstorz** [comment]
$ python -m pip install termios
ERROR: Could not find a version that satisfies the requirement termios (from versions: none)
ERROR: No matching distribution found for termios

**Comment by nschloe** [comment]
Duplicate of #12, #14, #26.

**Comment by conradstorz** [comment]
Sorry to have bothered you. I did not see the in-compatibility issue.
